import type { MediaAsset } from '@/types';
import { buildFilename, slugify } from '@/lib/utils';
import { logger } from '@/lib/logger';
import { flattenAsset } from '@/lib/export/client';

/**
 * Server-side export utilities for exports at or above the CLIENT_EXPORT_THRESHOLD (25+).
 * Uses exceljs for XLSX, jsPDF for PDF, jszip for ZIP.
 */

/** Export assets as XLSX on the server (exceljs with source-colored tabs) */
export async function serverExportXlsx(assets: MediaAsset[], prefix: string = 'export'): Promise<Buffer> {
  const ExcelJS = await import('exceljs');
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('Assets', {
    properties: { tabColor: { argb: 'FF7C3AED' } },
    views: [{ state: 'frozen', ySplit: 1 }],
  });

  // Header
  const flatData = assets.map(flattenAsset);
  const headers = Object.keys(flatData[0] ?? { id: '' });
  ws.columns = headers.map((key) => ({
    header: key,
    key,
    width: Math.max(key.length + 2, 15),
  }));

  // Style header
  const headerRow = ws.getRow(1);
  headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF7C3AED' },
  };

  // Data rows
  for (const row of flatData) {
    const r = ws.addRow(row);
    r.commit();
  }

  // Auto-fit columns
  ws.columns.forEach((col) => {
    let maxLen = col.header ? String(col.header).length : 10;
    col.eachCell?.((cell) => {
      const len = cell.value ? String(cell.value).length : 0;
      if (len > maxLen) maxLen = len;
    });
    col.width = Math.min(maxLen + 2, 60);
  });

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/** Export a single asset as PDF on the server */
export async function serverExportPdf(asset: MediaAsset): Promise<Buffer> {
  const { jsPDF } = await import('jspdf');
  await import('jspdf-autotable');
  const QRCode = await import('qrcode');

  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(asset.title, pageWidth - margin * 2);
  doc.text(titleLines, margin, 50);

  // Subtitle
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120);
  doc.text(`${asset.source.toUpperCase()} · ${asset.date}`, margin, 50 + titleLines.length * 24 + 10);

  let y = 50 + titleLines.length * 24 + 30;

  // Try to embed preview image
  if (asset.previewUrl || asset.fullUrl) {
    try {
      const imgUrl = asset.previewUrl || asset.fullUrl;
      const response = await fetch(imgUrl);
      const arrayBuffer = await response.arrayBuffer();
      const base64 = Buffer.from(arrayBuffer).toString('base64');
      const imgWidth = pageWidth - margin * 2;
      doc.addImage(base64, 'JPEG', margin, y, imgWidth, imgWidth * 0.5);
      y += imgWidth * 0.5 + 20;
    } catch {
      // Skip image
    }
  }

  // Metadata table
  const autoTable = (doc as unknown as { autoTable: (opts: Record<string, unknown>) => void }).autoTable;
  autoTable({
    startY: y,
    head: [['Field', 'Value']],
    body: [
      ['ID', asset.id],
      ['Native ID', asset.nativeId],
      ['Source', asset.source],
      ['Kind', asset.kind],
      ['Date', asset.date],
      ['Credit', asset.credit ?? '—'],
      ['Center', asset.center ?? '—'],
      ...Object.entries(asset.metadata).map(([k, v]) => [k, String(v)]),
    ],
    theme: 'striped',
    headStyles: { fillColor: [124, 58, 237] },
    margin: { left: margin, right: margin },
  });

  y = (doc as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 200;
  y += 20;

  // Description
  if (asset.description) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Description', margin, y);
    y += 16;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(asset.description, pageWidth - margin * 2);
    doc.text(descLines, margin, y);
    y += descLines.length * 14 + 20;
  }

  // QR code
  if (asset.citations[0]?.url) {
    try {
      const qrDataUrl = await QRCode.toDataURL(asset.citations[0].url, { width: 100 });
      doc.addImage(qrDataUrl, 'PNG', margin, y, 80, 80);
      doc.setFontSize(8);
      doc.text('Scan to view source', margin, y + 95);
    } catch {
      // Skip QR
    }
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated by Cosmos Vault · ${new Date().toISOString()}`,
    margin,
    footerY
  );

  return Buffer.from(doc.output('arraybuffer'));
}

/** Export assets as ZIP on the server (images + manifest + citations + README) */
export async function serverExportZip(assets: MediaAsset[], prefix: string = 'export'): Promise<Buffer> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  const capped = assets.slice(0, 50);

  const imageFolder = zip.folder('images');
  for (let i = 0; i < capped.length; i++) {
    const asset = capped[i]!;
    if (!asset.downloadUrl && !asset.fullUrl) continue;
    try {
      const response = await fetch(asset.downloadUrl ?? asset.fullUrl);
      const arrayBuffer = await response.arrayBuffer();
      const ext = asset.kind === 'video' ? 'mp4' : 'jpg';
      imageFolder?.file(
        `${String(i + 1).padStart(3, '0')}_${slugify(asset.title).slice(0, 40)}.${ext}`,
        arrayBuffer
      );
    } catch (err) {
      logger.warn('ZIP: failed to fetch image', { assetId: asset.id, error: (err as Error).message });
    }
  }

  zip.file(
    'manifest.json',
    JSON.stringify(
      {
        generated: new Date().toISOString(),
        source: 'Cosmos Vault',
        count: capped.length,
        assets: capped.map((a) => ({ id: a.id, title: a.title, source: a.source, date: a.date })),
      },
      null,
      2
    )
  );

  const citations = capped
    .flatMap((a) => a.citations.map((c) => `${a.title}: ${c.label} — ${c.url}`))
    .join('\n');
  zip.file('citations.txt', citations);

  zip.file(
    'README.txt',
    `Cosmos Vault Export\nGenerated: ${new Date().toISOString()}\nAssets: ${capped.length}\n\n` +
      `This ZIP contains images and metadata exported from NASA APIs via Cosmos Vault.\n` +
      `All imagery is credited to NASA and its respective missions.\n`
  );

  return zip.generateAsync({ type: 'nodebuffer' });
}

/** Export assets as CSV on the server (RFC 4180, UTF-8 BOM) */
export async function serverExportCsv(assets: MediaAsset[]): Promise<Buffer> {
  const XLSX = await import('xlsx');
  const flatData = assets.map(flattenAsset);
  const ws = XLSX.utils.json_to_sheet(flatData);
  const csv = XLSX.utils.sheet_to_csv(ws);
  return Buffer.from('\uFEFF' + csv, 'utf-8');
}

/** Export assets as JSON on the server */
export async function serverExportJson(assets: MediaAsset[]): Promise<Buffer> {
  return Buffer.from(JSON.stringify(assets, null, 2), 'utf-8');
}
